name: untitled
description: "RakshakAuth"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.3.0
  provider: ^6.1.2

  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  google_sign_in: ^6.1.6
  google_sign_in_web: ^0.12.4+4
  firebase_auth_web: ^5.9.2
  font_awesome_flutter: ^10.8.0
  firebase_database: ^11.3.4
  url_launcher: ^6.3.1
  restart_app: ^1.3.2
  data_table_2: ^2.6.0



flutter:
  uses-material-design: true
  assets:
    - assets/images/Background.png
    - assets/images/Google.png
    - assets/images/India.jpg
    - assets/images/Logo.png
    - assets/images/RA.png
    - assets/images/RA_background.png
    - assets/images/canva.jpeg
    - assets/images/coursera.png
    - assets/images/linkedin.png
    - assets/images/miro.png
    - assets/images/pinterest.png
    - assets/images/zoom.png
